---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: update-service-subscription
      namespace: openshift-update-service
      version: v1alpha1
