---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: all-openshift-clusters
placementRef:
  name: all-openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: cluster-info-header
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-rhacs
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-compliance
    apiGroup: policy.open-cluster-management.io
    kind: Policy