---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hcp-baremetal
  namespace: rhacm-config
placementRef:
  name: hcp-baremetal
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: hcp-bmh-console
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: hcp-openshift-samples-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-virtualization
    apiGroup: policy.open-cluster-management.io
    kind: Policy