---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-cluster
  namespace: rhacm-config
placementRef:
  name: hub-cluster
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: hub-ocp-update-svc
    apiGroup: policy.open-cluster-management.io
    kind: Policy