---
apiVersion: v1
kind: Secret
metadata:
  name: hypershift-bmh-raza-bmc-secret
  namespace: hypershift-bmh
stringData:
  password: n0tPassword
  username: ansible
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: hypershift-bmh-raza
  namespace: hypershift-bmh
  labels:
    infraenvs.agent-install.openshift.io: hypershift-bmh
    tenant-id: tenant2
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: raza
spec:
  automatedCleaningMode: disabled
  bmc:
    disableCertificateVerification: true
    credentialsName: hypershift-bmh-raza-bmc-secret
    # This address works for a SuperMicro BMC
    address: redfish-virtualmedia://192.168.46.40/redfish/v1/Systems/1
  # This is the MAC address of a non-BMC NIC
  bootMACAddress: 7C:C2:55:E3:1C:E4
  online: true
  rootDeviceHints:
    deviceName: /dev/disk/by-path/pci-0000:01:00.0-nvme-1
