---
apiVersion: v1
kind: Secret
metadata:
  name: hypershift-bmh-suki-bmc-secret
  namespace: hypershift-bmh
stringData:
  password: n0tPassword
  username: ansible
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: hypershift-bmh-suki
  namespace: hypershift-bmh
  labels:
    infraenvs.agent-install.openshift.io: hypershift-bmh
    tenant-id: tenant1
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: suki
spec:
  automatedCleaningMode: disabled
  bmc:
    disableCertificateVerification: true
    credentialsName: hypershift-bmh-suki-bmc-secret
    # This address works for a SuperMicro BMC
    address: redfish-virtualmedia://192.168.46.46/redfish/v1/Systems/1
  # This is a non-BMC MAC address - ironic will validate it against the list of MACs on the host
  bootMACAddress: 7C:C2:55:E1:7E:F8
  online: true
  rootDeviceHints:
    deviceName: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
