# pool ntp.kemo.labs iburst
# driftfile /var/lib/chrony/drift
# makestep 1.0 3
# rtcsync
# logdir /var/log/chrony

# cG9vbCBudHAua2Vtby5sYWJzIGlidXJzdApkcmlmdGZpbGUgL3Zhci9saWIvY2hyb255L2RyaWZ0Cm1ha2VzdGVwIDEuMCAzCnJ0Y3N5bmMKbG9nZGlyIC92YXIvbG9nL2Nocm9ueQo=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 999-chronyd-config
  #namespace: hcp-bmh
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
      name: 999-chronyd-config
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
          - contents:
              source: data:text/plain;charset=utf-8;base64,cG9vbCBudHAua2Vtby5sYWJzIGlidXJzdApkcmlmdGZpbGUgL3Zhci9saWIvY2hyb255L2RyaWZ0Cm1ha2VzdGVwIDEuMCAzCnJ0Y3N5bmMKbG9nZGlyIC92YXIvbG9nL2Nocm9ueQo=
            mode: 420
            overwrite: true
            path: /etc/chrony.conf