---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: hcp-bmh-raza
  #namespace: hcp-bmh
  labels:
    agent-install.openshift.io/bmh: hcp-bmh-raza
    infraenvs.agent-install.openshift.io: hcp-bmh
spec:
  config:
    interfaces:

      - name: eno1
        type: ethernet
        state: up
        lldp:
          enabled: false
      - name: eno2
        type: ethernet
        state: up
        lldp:
          enabled: false

      - name: eno3
        type: ethernet
        state: up
        lldp:
          enabled: false
      - name: eno4
        type: ethernet
        state: up
        lldp:
          enabled: false

      - name: bond0
        type: bond
        state: up
        lldp:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          port:
            - eno1
            - eno2

      - name: bond1
        type: bond
        state: up
        lldp:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          port:
            - eno3
            - eno4

      - name: bond0.70
        type: vlan
        state: up
        lldp:
          enabled: false
        vlan:
          id: 70
          base-iface: bond0
        ipv4:
          address:
            - ip: 192.168.70.40
              prefix-length: 23
          dhcp: false
          enabled: true

      - name: bond1.86
        type: vlan
        state: up
        lldp:
          enabled: false
        vlan:
          id: 86
          base-iface: bond1
        ipv4:
          address:
            - ip: 192.168.86.40
              prefix-length: 24
          dhcp: false
          enabled: true
    dns-resolver:
      config:
        search:
        - kemo.labs
        - kemo.network
        server:
        - 192.168.42.11
    routes:
      config:
        - destination: 0.0.0.0/0
          metric: 200
          next-hop-address: 192.168.70.1
          next-hop-interface: bond0.70
          table-id: 254
        - destination: 192.168.86.0/24
          metric: 150
          next-hop-address: 192.168.86.1
          next-hop-interface: bond1.86
          table-id: 254
  interfaces:
    - name: eno1
      macAddress: 7C:C2:55:E3:1C:E4
    - name: eno2
      macAddress: 7C:C2:55:E3:1C:E5
  # Mellanox NICs
    - name: eno3
      macAddress: 04:3f:72:bd:10:9a
    - name: eno4
      macAddress: 04:3f:72:bd:10:9b
