---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: error-pages
policyDefaults:
  namespace: rhacm-config
  placement:
    placementName: all-openshift-clusters
  remediationAction: enforce
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  severity: low
  categories:
    - OCPCM - OpenShift Configuration Management
  standards:
    - Kemo Labs 2025
  controls:
    - CBC - Cluster Baseline Configuration
  description: This policy generator creates a Policy to enforce the error pages for the default IngressController.
policies:
  - name: error-pages
    manifests:
      - path: manifests