apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- mce_mirror-registry-config.yaml

configMapGenerator:
- behavior: merge
  envs:
  - env.proxy
  name: assisted-service-config
  namespace: multicluster-engine

patches:
- path: mce_agentserviceconfig.yaml
