# File: pipeline-ee-base.yml
parameters:
  - name: REGISTRY_HOSTNAME # The hostname of the registry to push to
    type: string
    default: "quay.io"
  - name: REGISTRY_PATH     # Path to push to in the registry, eg your username
    type: string
    default: ""

  - name: REGISTRY_USERNAME # Needed for target push registry login
    type: string
    default: ""
  - name: REGISTRY_PASSWORD # Needed for target push registry login
    type: string
    default: ""

  - name: EE_IMAGE_NAME     # Image Name for the EE
    type: string
    default: ""
  - name: EE_IMAGE_TAG      # Image tag, must be one tag for image build, defaults to latest
    type: string
    default: "latest"
  - name: EE_FOLDER_NAME    # Name of the folder in the repo where the EE is located
    type: string
    default: ""

stages:
  - stage: build_ee

    variables:
      - name: currentDate
        value: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
      - name: sourceVersion
        value: $(Build.SourceVersion)

    pool:
      vmImage: ubuntu-latest

    jobs:
      - job: build
        displayName: Build EE
        steps:
          - bash: |
              if [ -z "$REGISTRY_USERNAME" ]; then
                echo "REGISTRY_USERNAME was not provided!"
                exit 1
              fi
              if [ -z "$REGISTRY_PASSWORD" ]; then
                echo "REGISTRY_PASSWORD was not provided!"
                exit 1
              fi
              if [ -z "$EE_IMAGE_NAME" ]; then
                echo "EE_IMAGE_NAME was not provided!"
                exit 1
              fi
            env:
              REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
              REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
              EE_IMAGE_NAME: ${{ parameters['EE_IMAGE_NAME'] }}

          - script: |
              commitHash=${sourceVersion:0:7}
              echo "Git Commit: ${sourceVersion}"
              echo "Short Git Commit: ${commitHash}"
              echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
            env: { sourceVersion: $(Build.SourceVersion) }

          - script: pip install ansible-builder==3.0.0

          - script: sudo apt-get install podman -y

          - bash: |
              ansible-builder build \
              --tag=${{ parameters.EE_IMAGE_NAME }}:${{ parameters.EE_IMAGE_TAG }} \
              --tag=${{ parameters.EE_IMAGE_NAME }}:$(commitHash) \
              --tag=${{ parameters.EE_IMAGE_NAME }}:$(sourceVersion) \
              --tag=${{ parameters.EE_IMAGE_NAME }}:$(currentDate)
            env:
              REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
              REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
              EE_IMAGE_NAME: ${{ parameters['EE_IMAGE_NAME'] }}
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.EE_FOLDER_NAME }}"

          - bash: |
              podman login ${REGISTRY_HOSTNAME} -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}

              podman tag ${EE_IMAGE_NAME}:${EE_IMAGE_TAG} ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:${EE_IMAGE_TAG}
              podman tag ${EE_IMAGE_NAME}:$(commitHash) ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(commitHash)
              podman tag ${EE_IMAGE_NAME}:$(sourceVersion) ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(sourceVersion)
              podman tag ${EE_IMAGE_NAME}:$(currentDate) ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(currentDate)

              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:${EE_IMAGE_TAG}
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(commitHash)
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(sourceVersion)
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${EE_IMAGE_NAME}:$(currentDate)
            env:
              REGISTRY_HOSTNAME: ${{ parameters.REGISTRY_HOSTNAME }}
              REGISTRY_PATH: ${{ parameters.REGISTRY_PATH }}
              REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
              REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
              EE_IMAGE_NAME: ${{ parameters['EE_IMAGE_NAME'] }}
              EE_IMAGE_TAG: ${{ parameters['EE_IMAGE_TAG'] }}
              