---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  labels:
    enabled.external-dns.kemo.labs: 'true'
  name: hcp-virt-api
  namespace: hypershift-virt
spec:
  endpoints:
    - dnsName: api.hypershift-virt.apps.endurance-sno.lab.kemo.network
      recordTTL: 60
      recordType: A
      targets:
        - 192.168.70.109