# this isn't really secret?  it's a public key?
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-cluster-hypershift-virt
  namespace: 'clusters'
data:
  id_rsa.pub: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDL1VRNlNWSjBKay9mRGZMcGVjSUlJZlRlMytSeStvYUY4QUZLQVp3WEo4eE1NbXJQY1BYMUpUYjRrL2tlVlBUNWxpcVlMYjZweE85eUtVYjFmTElLWFFqKzZPYURGYXE3SjhPM2FkNUFqcHdNSDk3cHluUHRqVW5sdERJUGJNVExPVUhNWkNydkYvUEluMGlRMmxmbDQ4bEFERC9TL3RPUGgzNFRJOGZ2K21pdUNPN0dkc2s5RHFUOVN4SVJHNG9LajdaS3AvUEt5V3VQaGVSaEowS2lTZUZJSFIzZFhTSm5MaUwrSmtkQm90QjRJSzc4UHlnd282UDZXeWwyUDRnb2JrS2h5L1l1VGlTSW1iYU4wRzhZTUpyVXUxRXpZUTVRbG1OcVBLVnVGSDh0ZTQxdnhtVFg0N041aDh2Zk85YzAwWUZDNUg5bXRzUE1HWFlSVGlSa0I=

