apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  LOG_LEVEL: "debug"
  AUTH_TYPE: "none"
  SKIP_CERT_VERIFICATION: "True"
  ISO_IMAGE_TYPE: "full-iso"

  # ========================================================================================
  # Disconnected/Private Registry Configuration
  # ========================================================================================
  # HTTP_PROXY: "http://proxy.kemo.labs:3129"
  # HTTPS_PROXY: "http://proxy.kemo.labs:3129"
  # NO_PROXY: ".kemo.labs,.kemo.network,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,localhost,127.0.0.1,.svc,.local"