---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ca-configmap.yaml
  - config-configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

namespace: multicluster-engine