---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: 'hcp-bmh1'
  namespace: 'hcp-bmh'
  labels:
    "cluster.open-cluster-management.io/clusterset": 'default'
    hcp-bmh-cluster: "true"
spec:
  # Either SingleReplica or HighlyAvailable
  controllerAvailabilityPolicy: SingleReplica
  infrastructureAvailabilityPolicy: SingleReplica

  # OpenShift Release Image location
  release:
    # If connected to the internet, or with ITMS
    image: quay.io/openshift-release-dev/ocp-release:4.17.12-x86_64
    # If disconnected from the internet, mirror/proxy registry used
    #image: quay-ptc.jfrog.lab.kemo.network/openshift-release-dev/ocp-release:4.17.12-x86_64

  # Base DNS domain for the cluster - cluster name is from the name of this object is prepended to this
  dns:
    baseDomain: 'd70.lab.kemo.network'

  # Agent/Assisted Service BMH installation method
  platform:
    type: Agent
    agent:
      agentNamespace: 'hcp-bmh'
  # infraID is the InfraEnv name
  infraID: 'hcp-bmh'

  # If doing multi-cluster networking, make sure to set these to different ranges between the clusters - the examples already do so
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
    networkType: OVNKubernetes

  # General configuration
  pullSecret:
    name: pull-secret
  sshKey:
    name: ssh-pub-key
  olmCatalogPlacement: guest
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route

  # ========================================================================================
  # Disconnected/Private Registry Configuration
  # ========================================================================================

  additionalTrustBundle:
    name: user-ca-bundle
  configuration:
    image:
      additionalTrustedCA:
        name: user-ca-bundle

#  imageContentSources:
#  - source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
#    mirrors:
#      - quay-ptc.jfrog.lab.kemo.network/openshift-release-dev/ocp-v4.0-art-dev
#  - source: quay.io/openshift-release-dev/ocp-release
#    mirrors:
#      - quay-ptc.jfrog.lab.kemo.network/openshift-release-dev/ocp-release
#  - source: quay.io
#    mirrors:
#      - quay-ptc.jfrog.lab.kemo.network
#  - source: registry.redhat.io
#    mirrors:
#      - registry-redhat-ptc.jfrog.lab.kemo.network
#  - source: registry.connect.redhat.com
#    mirrors:
#      - registry-connect-redhat-ptc.jfrog.lab.kemo.network