---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
spec:

  # ========================================================================================
  # Disconnected/Private Registry Configuration
  # ========================================================================================

  storageImport:
    # Disable TLS validation for the private registry
    # Or use the certConfigMap parameter to provide the CA certificate as shown below
    insecureRegistries:
      - quay-ptc.jfrog.lab.kemo.network

  # In disconnected environments you have to specifically tell the operator to use the disconnected registry
  # It doesn't pick it up from the global cluster mirror configuration :)
  # You can source the default values provided by the operator by looking at the .status and copying the values, modifying them as needed, and then applying the changes to the .spec
  # The operator will then apply the changes to the cluster
  # Below is an example of how to configure the operator to use a disconnected registry for the default boot sources
  dataImportCronTemplates:
    - metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        labels:
          kubevirt.io/dynamic-credentials-support: 'true'
        name: centos-stream8-image-cron
      spec:
        garbageCollect: Outdated
        managedDataSource: centos-stream8
        schedule: 30 7/12 * * *
        template:
          metadata: {}
          spec:
            source:
              registry:
                pullMethod: node
                url: 'docker://disconn-harbor.d70.kemo.labs/quay-ptc/containerdisks/centos-stream:8'
                secretRef: private-ps
            storage:
              resources:
                requests:
                  storage: 30Gi
    - metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        labels:
          kubevirt.io/dynamic-credentials-support: 'true'
        name: centos-stream9-image-cron
      spec:
        garbageCollect: Outdated
        managedDataSource: centos-stream9
        schedule: 30 7/12 * * *
        template:
          metadata: {}
          spec:
            source:
              registry:
                pullMethod: node
                url: 'docker://disconn-harbor.d70.kemo.labs/quay-ptc/containerdisks/centos-stream:9'
                secretRef: private-ps
            storage:
              resources:
                requests:
                  storage: 30Gi
    - metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        labels:
          kubevirt.io/dynamic-credentials-support: 'true'
        name: centos-stream10-image-cron
      spec:
        garbageCollect: Outdated
        managedDataSource: centos-stream10
        schedule: 30 7/12 * * *
        template:
          metadata: {}
          spec:
            source:
              registry:
                pullMethod: node
                url: 'docker://disconn-harbor.d70.kemo.labs/quay-ptc/containerdisks/centos-stream:10'
                secretRef: private-ps
                certConfigMap: private-registry-ca
            storage:
              resources:
                requests:
                  storage: 30Gi
    - metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        labels:
          kubevirt.io/dynamic-credentials-support: 'true'
        name: fedora40-image-cron
      spec:
        garbageCollect: Outdated
        managedDataSource: fedora
        schedule: 30 7/12 * * *
        template:
          metadata: {}
          spec:
            source:
              registry:
                pullMethod: node
                url: 'docker://disconn-harbor.d70.kemo.labs/quay-ptc/containerdisks/fedora:40'
                secretRef: private-ps
            storage:
              resources:
                requests:
                  storage: 30Gi
    - metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        labels:
          kubevirt.io/dynamic-credentials-support: 'true'
        name: ubuntu2404-image-cron
      spec:
        garbageCollect: Outdated
        managedDataSource: ubuntu2404
        schedule: 30 7/12 * * *
        template:
          metadata: {}
          spec:
            source:
              registry:
                pullMethod: node
                url: 'docker://disconn-harbor.d70.kemo.labs/quay-ptc/containerdisks/ubuntu:24.04'
                secretRef: private-ps
                certConfigMap: private-registry-ca
            storage:
              resources:
                requests:
                  storage: 30Gi