# Yes, you have to create the pull secret in two places...
---
kind: Secret
apiVersion: v1
metadata:
  name: private-ps
  namespace: openshift-cnv
stringData:
  # accessKeyId: username
  # secretKey: password
  accessKeyId: r-lab-ocp-puller
  secretKey: QS3ossaPl5wNi2mfCURGM0eJcrvTOTCK
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: private-ps
  namespace: openshift-virtualization-os-images
stringData:
  # accessKeyId: username
  # secretKey: password
  accessKeyId: r-lab-ocp-puller
  secretKey: QS3ossaPl5wNi2mfCURGM0eJcrvTOTCK
type: Opaque