# Install the Helm Chart after deploying this
# helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/
# helm repo update
# helm upgrade --install -f values.yaml -n external-dns external-dns external-dns/external-dns
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - rbac.yaml
  - pdns-secret.yaml
  - namespace.yaml
