---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cluster-info-header
  annotations:
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CBC - Cluster Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-info-header
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - cluster-info-header
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleNotification
                metadata:
                  name: cluster-info-header
                spec:
                  backgroundColor: '#0088ce'
                  color: '#fff'
                  location: BannerTop
                  text: 'You are on {{hub .ManagedClusterName hub}} cluster!'
