---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # Global/Common Policies
  - console-info-header.yaml
  - openshift-samples-config.yaml

  # RHACM Hub Policies
  #- hub-ocp-update-svc.yaml

  # Operator Installation Policies
  - operators-rhacs.yaml
  - operators-pipelines.yaml
  - operators-compliance.yaml
  - operators-virtualization.yaml

  # Hosted Control Plane, Bare Metal Policies
  - hcp-bmh-console.yaml

  # Hosted Control Plane, KubeVirt Policies