---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: hcp-openshift-samples-config
  annotations:
    policy.open-cluster-management.io/description: Configures the OpenShift Samples Operator
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CBC - Cluster Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-samples-config
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: samples.operator.openshift.io/v1
                kind: Config
                metadata:
                  name: cluster
                spec:
                  architectures:
                    - x86_64
                  managementState: Managed
                  samplesRegistry: disconn-harbor.d70.kemo.labs/registry-redhat-io-ptc